apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    tier: service
spec:
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  type: LoadBalancer
  selector:
    app: nginx

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.9
        ports:
        - containerPort: 80
        - containerPort: 443
